name: Release

on:
  push:
    tags:
      - 'v*'

# Add permissions block
permissions:
  contents: write  # Required for creating releases and uploading artifacts

jobs:
  test:
    uses: "./.github/workflows/test.yml"
  build:
    name: Build
    needs: [test]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux-amd64
            ext: ""
          - os: ubuntu-latest
            name: linux-arm64
            ext: ""
            goarch: arm64
          - os: macos-latest
            name: darwin-amd64
            ext: ""
          - os: macos-latest
            name: darwin-arm64
            ext: ""
            goarch: arm64
          - os: windows-latest
            name: windows-amd64
            ext: ".exe"

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        env:
          GOOS: ${{ matrix.name == 'windows-amd64' && 'windows' || matrix.name == 'darwin-amd64' && 'darwin' || matrix.name == 'darwin-arm64' && 'darwin' || 'linux' }}
          GOARCH: ${{ matrix.goarch || 'amd64' }}
        run: |
          go build -o parseachangelog${{ matrix.ext }} ./main.go
          tar -czf parseachangelog-${{ matrix.name }}.tar.gz parseachangelog${{ matrix.ext }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: parseachangelog-${{ matrix.name }}
          path: parseachangelog-${{ matrix.name }}.tar.gz

  release:
    name: Create Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/parseachangelog-*/parseachangelog-*.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
