name: Release

on:
  push:
    tags:
      - 'v*'

# Add permissions block
permissions:
  contents: write  # Required for creating releases and uploading artifacts

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            name: linux-amd64
            ext: ""
          - os: ubuntu-latest
            name: linux-arm64
            ext: ""
            goarch: arm64
          - os: macos-latest
            name: darwin-amd64
            ext: ""
          - os: macos-latest
            name: darwin-arm64
            ext: ""
            goarch: arm64
          - os: windows-latest
            name: windows-amd64
            ext: ".exe"

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        env:
          GOOS: ${{ matrix.name == 'windows-amd64' && 'windows' || matrix.name == 'darwin-amd64' && 'darwin' || matrix.name == 'darwin-arm64' && 'darwin' || 'linux' }}
          GOARCH: ${{ matrix.goarch || 'amd64' }}
        run: |
          go build -o parseachangelog${{ matrix.ext }} ./main.go
          tar -czf parseachangelog-${{ matrix.name }}.tar.gz parseachangelog${{ matrix.ext }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: parseachangelog-${{ matrix.name }}
          path: parseachangelog-${{ matrix.name }}.tar.gz

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/parseachangelog-*/parseachangelog-*.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-homebrew:
    name: Update Homebrew Formula
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Calculate SHA256 hashes
        id: sha256
        run: |
          echo "darwin-amd64=$(shasum -a 256 artifacts/parseachangelog-darwin-amd64/parseachangelog-darwin-amd64.tar.gz | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          echo "darwin-arm64=$(shasum -a 256 artifacts/parseachangelog-darwin-arm64/parseachangelog-darwin-arm64.tar.gz | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          echo "linux-amd64=$(shasum -a 256 artifacts/parseachangelog-linux-amd64/parseachangelog-linux-amd64.tar.gz | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          echo "linux-arm64=$(shasum -a 256 artifacts/parseachangelog-linux-arm64/parseachangelog-linux-arm64.tar.gz | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - name: Update formula version and hashes
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/version \".*\"/version \"$VERSION\"/" homebrew/parseachangelog.rb
          sed -i "s|url \".*darwin-amd64.tar.gz\"|url \"https://github.com/ridakk/parseachangelog/releases/download/v$VERSION/parseachangelog-darwin-amd64.tar.gz\"|" homebrew/parseachangelog.rb
          sed -i "s|url \".*darwin-arm64.tar.gz\"|url \"https://github.com/ridakk/parseachangelog/releases/download/v$VERSION/parseachangelog-darwin-arm64.tar.gz\"|" homebrew/parseachangelog.rb
          sed -i "s|url \".*linux-amd64.tar.gz\"|url \"https://github.com/ridakk/parseachangelog/releases/download/v$VERSION/parseachangelog-linux-amd64.tar.gz\"|" homebrew/parseachangelog.rb
          sed -i "s|url \".*linux-arm64.tar.gz\"|url \"https://github.com/ridakk/parseachangelog/releases/download/v$VERSION/parseachangelog-linux-arm64.tar.gz\"|" homebrew/parseachangelog.rb
          sed -i "s/sha256 \".*\" # darwin-amd64/sha256 \"${{ steps.sha256.outputs.darwin-amd64 }}\" # darwin-amd64/" homebrew/parseachangelog.rb
          sed -i "s/sha256 \".*\" # darwin-arm64/sha256 \"${{ steps.sha256.outputs.darwin-arm64 }}\" # darwin-arm64/" homebrew/parseachangelog.rb
          sed -i "s/sha256 \".*\" # linux-amd64/sha256 \"${{ steps.sha256.outputs.linux-amd64 }}\" # linux-amd64/" homebrew/parseachangelog.rb
          sed -i "s/sha256 \".*\" # linux-arm64/sha256 \"${{ steps.sha256.outputs.linux-arm64 }}\" # linux-arm64/" homebrew/parseachangelog.rb

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add homebrew/parseachangelog.rb
          git commit -m "Update Homebrew formula to version ${GITHUB_REF#refs/tags/v}"
          git push
