name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...

      - name: Run coverage
        if: matrix.os != 'windows-latest'
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: Run coverage (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
        shell: bash

      - name: Upload coverage artifact
        uses: codecov/codecov-action@v5
        with:
          name: coverage-${{ matrix.os }}
          path: coverage.out
